### ISSUE TITLE
Using a template

### ISSUE THREAD

**Issue by jherrero** [lazappi/twitter-stats#1]
Hi @lazappi 

I have been working a little on the code and decided to use a template rather than copy&paste the code for every meeting. Also, I have merged the plots for original and retweets in a single plot to make the report a little more compact.

Feel free to re-use!

https://github.com/jherrero/twitter-stats/blob/master/analysis/template.Rmd

**Comment by lazappi** [comment]
Nice! I've been lazy about making a template, mostly because I tend to add things each time I do it and it seemed easier just to copy an old one. I hadn't thought of using a child document though, that's a cool idea. So is combining the original/retweets, I had them separate based on the stuff I used from Neil Saunders but it's maybe not necessary. I might steal these ideas next time I do this 😸.

I noticed you have deleted the output files from your repository. How are you hosting the HTML files now?

**Comment by jherrero** [comment]
Ah, I am not used to gihub.io and followed a tutorial that explained how to create them by setting up a repo called username.github.io. I can now see that you can serve them directly from the docs folder of the master branch, which is much easier!

I will change that as soon as I have some time.
